/**
 * Texture resolver — maps item IDs to local texture paths
 * Textures are stored in public/textures/ and served by Vite
 */

// Mapping of item IDs to their texture file paths
// Key: item ID (e.g., "minecraft:iron_ingot")
// Value: path relative to textures base (e.g., "minecraft/iron_ingot.png")
const TEXTURE_MAP: Record<string, string> = {
  // ─── Vanilla items ───
  'minecraft:iron_ingot':       'minecraft/iron_ingot.png',
  'minecraft:gold_ingot':       'minecraft/gold_ingot.png',
  'minecraft:copper_ingot':     'minecraft/copper_ingot.png',
  'minecraft:diamond':          'minecraft/diamond.png',
  'minecraft:emerald':          'minecraft/emerald.png',
  'minecraft:redstone':         'minecraft/redstone.png',
  'minecraft:coal':             'minecraft/coal.png',
  'minecraft:charcoal':         'minecraft/charcoal.png',
  'minecraft:quartz':           'minecraft/quartz.png',
  'minecraft:lapis_lazuli':     'minecraft/lapis_lazuli.png',
  'minecraft:netherite_ingot':  'minecraft/netherite_ingot.png',
  'minecraft:netherite_scrap':  'minecraft/netherite_scrap.png',
  'minecraft:stick':            'minecraft/stick.png',
  'minecraft:book':             'minecraft/book.png',
  'minecraft:paper':            'minecraft/paper.png',
  'minecraft:string':           'minecraft/string.png',
  'minecraft:feather':          'minecraft/feather.png',
  'minecraft:leather':          'minecraft/leather.png',
  'minecraft:flint':            'minecraft/flint.png',
  'minecraft:iron_nugget':      'minecraft/iron_nugget.png',
  'minecraft:gold_nugget':      'minecraft/gold_nugget.png',
  'minecraft:blaze_rod':        'minecraft/blaze_rod.png',
  'minecraft:ender_pearl':      'minecraft/ender_pearl.png',
  'minecraft:slime_ball':       'minecraft/slime_ball.png',
  'minecraft:gunpowder':        'minecraft/gunpowder.png',
  'minecraft:wheat':            'minecraft/wheat.png',
  'minecraft:sugar_cane':       'minecraft/sugar_cane.png',
  'minecraft:apple':            'minecraft/apple.png',
  'minecraft:bone':             'minecraft/bone.png',
  'minecraft:nether_star':      'minecraft/nether_star.png',
  'minecraft:bucket':           'minecraft/bucket.png',
  'minecraft:lava_bucket':      'minecraft/lava_bucket.png',
  'minecraft:water_bucket':     'minecraft/water_bucket.png',

  // Vanilla tools & armor
  'minecraft:iron_pickaxe':     'minecraft/iron_pickaxe.png',
  'minecraft:iron_axe':         'minecraft/iron_axe.png',
  'minecraft:iron_shovel':      'minecraft/iron_shovel.png',
  'minecraft:iron_hoe':         'minecraft/iron_hoe.png',
  'minecraft:iron_sword':       'minecraft/iron_sword.png',
  'minecraft:iron_helmet':      'minecraft/iron_helmet.png',
  'minecraft:iron_chestplate':  'minecraft/iron_chestplate.png',
  'minecraft:iron_leggings':    'minecraft/iron_leggings.png',
  'minecraft:iron_boots':       'minecraft/iron_boots.png',
  'minecraft:diamond_pickaxe':  'minecraft/diamond_pickaxe.png',
  'minecraft:diamond_axe':      'minecraft/diamond_axe.png',
  'minecraft:diamond_shovel':   'minecraft/diamond_shovel.png',
  'minecraft:diamond_hoe':      'minecraft/diamond_hoe.png',
  'minecraft:diamond_sword':    'minecraft/diamond_sword.png',
  'minecraft:diamond_helmet':   'minecraft/diamond_helmet.png',
  'minecraft:diamond_chestplate':'minecraft/diamond_chestplate.png',
  'minecraft:diamond_leggings': 'minecraft/diamond_leggings.png',
  'minecraft:diamond_boots':    'minecraft/diamond_boots.png',
  'minecraft:golden_pickaxe':   'minecraft/golden_pickaxe.png',
  'minecraft:golden_axe':       'minecraft/golden_axe.png',
  'minecraft:golden_shovel':    'minecraft/golden_shovel.png',
  'minecraft:golden_hoe':       'minecraft/golden_hoe.png',
  'minecraft:golden_sword':     'minecraft/golden_sword.png',
  'minecraft:golden_helmet':    'minecraft/golden_helmet.png',
  'minecraft:golden_chestplate':'minecraft/golden_chestplate.png',
  'minecraft:golden_leggings':  'minecraft/golden_leggings.png',
  'minecraft:golden_boots':     'minecraft/golden_boots.png',
  'minecraft:bow':              'minecraft/bow.png',
  'minecraft:arrow':            'minecraft/arrow.png',
  'minecraft:flint_and_steel':  'minecraft/flint_and_steel.png',
  'minecraft:bone_meal':        'minecraft/bone_meal.png',
  'minecraft:bread':            'minecraft/bread.png',
  'minecraft:sugar':            'minecraft/sugar.png',
  'minecraft:golden_apple':     'minecraft/golden_apple.png',
  'minecraft:torch':            'minecraft/torch.png',
  'minecraft:redstone_torch':   'minecraft/redstone_torch.png',
  'minecraft:lever':            'minecraft/lever.png',
  'minecraft:iron_door':        'minecraft/iron_door.png',
  'minecraft:iron_trapdoor':    'minecraft/iron_trapdoor.png',
  'minecraft:tnt':              'minecraft/tnt.png',
  'minecraft:beacon':           'minecraft/beacon.png',
  'minecraft:lodestone':        'minecraft/lodestone.png',
  'minecraft:rail':             'minecraft/rail.png',
  'minecraft:powered_rail':     'minecraft/powered_rail.png',
  'minecraft:redstone_repeater':'minecraft/redstone_repeater.png',
  'minecraft:comparator':       'minecraft/comparator.png',
  'minecraft:enchanting_table': 'minecraft/enchanting_table.png',
  'minecraft:anvil':            'minecraft/block/anvil_top.png',

  // Vanilla block textures
  'minecraft:stone':            'minecraft/block/stone.png',
  'minecraft:cobblestone':      'minecraft/block/cobblestone.png',
  'minecraft:andesite':         'minecraft/block/andesite.png',
  'minecraft:diorite':          'minecraft/block/diorite.png',
  'minecraft:granite':          'minecraft/block/granite.png',
  'minecraft:oak_planks':       'minecraft/block/oak_planks.png',
  'minecraft:oak_log':          'minecraft/block/oak_log_top.png',
  'minecraft:glass':            'minecraft/block/glass.png',
  'minecraft:obsidian':         'minecraft/block/obsidian.png',
  'minecraft:crafting_table':   'minecraft/block/crafting_table_front.png',
  'minecraft:furnace':          'minecraft/block/furnace_front.png',
  'minecraft:chest':            'minecraft/entity/normal.png',
  'minecraft:hopper':           'minecraft/block/hopper_outside.png',
  'minecraft:piston':           'minecraft/block/piston_top.png',
  'minecraft:sticky_piston':    'minecraft/block/piston_top_sticky.png',
  'minecraft:observer':         'minecraft/block/observer_front.png',
  'minecraft:dispenser':        'minecraft/block/dispenser_front.png',
  'minecraft:dropper':          'minecraft/block/dropper_front.png',
  'minecraft:chiseled_stone_bricks':'minecraft/block/chiseled_stone_bricks.png',
  'minecraft:netherite_block':  'minecraft/block/netherite_block.png',
  'minecraft:diamond_block':    'minecraft/block/diamond_block.png',
  'minecraft:gold_block':       'minecraft/block/gold_block.png',
  'minecraft:iron_block':       'minecraft/block/iron_block.png',
  'minecraft:copper_block':     'minecraft/block/copper_block.png',
  'minecraft:coal_block':       'minecraft/block/coal_block.png',
  'minecraft:lapis_block':      'minecraft/block/lapis_block.png',
  'minecraft:emerald_block':    'minecraft/block/emerald_block.png',
  'minecraft:sand':             'minecraft/block/sand.png',

  // ─── Mekanism ───
  'mekanism:osmium_ingot':      'mekanism/ingot_osmium.png',
  'mekanism:tin_ingot':         'mekanism/ingot_tin.png',
  'mekanism:lead_ingot':        'mekanism/ingot_lead.png',
  'mekanism:uranium_ingot':     'mekanism/ingot_uranium.png',
  'mekanism:bronze_ingot':      'mekanism/ingot_bronze.png',
  'mekanism:steel_ingot':       'mekanism/ingot_steel.png',
  'mekanism:osmium_ore':        'mekanism/raw_osmium.png',
  'mekanism:tin_ore':           'mekanism/raw_tin.png',
  'mekanism:lead_ore':          'mekanism/raw_lead.png',
  'mekanism:uranium_ore':       'mekanism/raw_uranium.png',
  'mekanism:fluorite_gem':      'mekanism/fluorite_gem.png',
  'mekanism:control_circuit_basic':    'mekanism/basic_control_circuit.png',
  'mekanism:control_circuit_advanced': 'mekanism/advanced_control_circuit.png',
  'mekanism:control_circuit_elite':    'mekanism/elite_control_circuit.png',
  'mekanism:control_circuit_ultimate': 'mekanism/ultimate_control_circuit.png',
  'mekanism:alloy_atomic':      'mekanism/alloy_atomic.png',
  'mekanism:alloy_infused':     'mekanism/alloy_infused.png',
  'mekanism:alloy_reinforced':  'mekanism/alloy_reinforced.png',
  'mekanism:enriched_diamond':  'mekanism/enriched_diamond.png',
  'mekanism:enriched_gold':     'mekanism/enriched_gold.png',
  'mekanism:enriched_iron':     'mekanism/enriched_iron.png',
  'mekanism:enriched_osmium':   'mekanism/enriched_refined_obsidian.png',
  'mekanism:enriched_redstone': 'mekanism/enriched_redstone.png',
  'mekanism:enriched_tin':      'mekanism/enriched_tin.png',
  'mekanism:substrate':         'mekanism/substrate.png',
  'mekanism:hdpe_rod':          'mekanism/hdpe_rod.png',
  'mekanism:hdpe_sheet':        'mekanism/hdpe_sheet.png',
  'mekanism:bio_fuel':          'mekanism/bio_fuel.png',
  'mekanism:polonium_pellet':   'mekanism/polonium_pellet.png',
  'mekanism:basic_energy_cube':    'mekanism/block/basic_induction_cell.png',
  'mekanism:advanced_energy_cube': 'mekanism/block/advanced_induction_cell.png',
  'mekanism:elite_energy_cube':    'mekanism/block/elite_induction_cell.png',
  'mekanism:ultimate_energy_cube': 'mekanism/block/ultimate_induction_cell.png',
  'mekanism:enrichment_chamber':          'mekanism/block/basic_induction_cell.png',
  'mekanism:metallurgic_infuser':         'mekanism/block/elite_induction_cell.png',
  'mekanism:combiner':                    'mekanism/block/advanced_induction_cell.png',
  'mekanism:crusher':                     'mekanism/block/ultimate_induction_cell.png',
  'mekanism:purification_chamber':        'mekanism/block/advanced_induction_cell.png',
  'mekanism:chemical_injection_chamber':  'mekanism/block/elite_induction_cell.png',
  'mekanism:digital_miner':               'mekanism/block/ultimate_induction_cell.png',

  // ─── Create ───
  'create:andesite_alloy':      'create/andesite_alloy.png',
  'create:brass_ingot':         'create/brass_ingot.png',
  'create:zinc_ingot':          'create/zinc_ingot.png',
  'create:iron_sheet':          'create/iron_sheet.png',
  'create:copper_sheet':        'create/copper_sheet.png',
  'create:brass_sheet':         'create/brass_sheet.png',
  'create:precision_mechanism': 'create/precision_mechanism.png',
  'create:cogwheel':            'create/block/cogwheel.png',
  'create:large_cogwheel':      'create/block/large_cogwheel.png',
  'create:shaft':               'create/block/gantry_shaft.png',
  'create:gearbox':             'create/block/gearbox.png',
  'create:mechanical_piston':   'create/block/piston_bottom.png',
  'create:mechanical_bearing':  'create/block/mechanical_bearing_side.png',
  'create:water_wheel':         'create/block/waterwheel_metal.png',
  'create:large_water_wheel':   'create/block/waterwheel_metal.png',
  'create:windmill_bearing':    'create/block/windmill_bearing_side.png',
  'create:belt_connector':      'create/block/belt.png',
  'create:andesite_casing':     'create/block/andesite_casing.png',
  'create:brass_casing':        'create/block/brass_casing.png',
  'create:copper_casing':       'create/block/copper_casing.png',
  'create:depot':               'create/block/belt.png',
  'create:chute':               'create/block/chute.png',
  'create:smart_chute':         'create/block/chute.png',
  'create:andesite_funnel':     'create/block/andesite_casing.png',
  'create:brass_funnel':        'create/block/brass_casing.png',
  'create:andesite_tunnel':     'create/block/andesite_casing.png',
  'create:brass_tunnel':        'create/block/brass_casing.png',
  'create:crushing_wheel':      'create/block/crushing_wheel.png',
  'create:mechanical_press':    'create/block/mechanical_press.png',
  'create:mechanical_mixer':    'create/block/mechanical_mixer.png',
  'create:mechanical_saw':      'create/block/mechanical_saw.png',
  'create:piston_extension_pole':'create/block/piston_bottom.png',

  // ─── Thermal ───
  'thermal:tin_ingot':          'thermal/tin_ingot.png',
  'thermal:lead_ingot':         'thermal/lead_ingot.png',
  'thermal:silver_ingot':       'thermal/silver_ingot.png',
  'thermal:nickel_ingot':       'thermal/nickel_ingot.png',
  'thermal:bronze_ingot':       'thermal/bronze_ingot.png',
  'thermal:constantan_ingot':   'thermal/constantan_ingot.png',
  'thermal:electrum_ingot':     'thermal/electrum_ingot.png',
  'thermal:invar_ingot':        'thermal/invar_ingot.png',
  'thermal:steel_ingot':        'thermal/invar_ingot.png',
  'thermal:signalum_ingot':     'thermal/electrum_ingot.png',
  'thermal:lumium_ingot':       'thermal/electrum_ingot.png',
  'thermal:enderium_ingot':     'thermal/electrum_ingot.png',
  'thermal:redstone_servo':     'thermal/electrum_gear.png',
  'thermal:rf_coil':            'thermal/electrum_nugget.png',
  'thermal:machine_frame':      'thermal/machine_frame.png',
  'thermal:pulverizer':         'thermal/machine_frame.png',
  'thermal:induction_smelter':  'thermal/machine_frame.png',
  'thermal:fluid_encapsulator': 'thermal/machine_frame.png',
  'thermal:centrifuge':         'thermal/machine_frame.png',
  'thermal:refinery':           'thermal/machine_frame.png',
  'thermal:crystallizer':       'thermal/machine_frame.png',
  'thermal:press':              'thermal/machine_frame.png',
  'thermal:upgrade_augment_1':  'thermal/machine_frame.png',
  'thermal:upgrade_augment_2':  'thermal/machine_frame.png',
  'thermal:upgrade_augment_3':  'thermal/machine_frame.png',

  // ─── AE2 ───
  'ae2:silicon':                'ae2/silicon.png',
  'ae2:certus_quartz_crystal':  'ae2/certus_quartz_crystal.png',
  'ae2:charged_certus_quartz_crystal':'ae2/charged_certus_quartz_crystal.png',
  'ae2:certus_quartz_dust':     'ae2/certus_quartz_dust.png',
  'ae2:fluix_crystal':          'ae2/fluix_crystal.png',
  'ae2:fluix_dust':             'ae2/fluix_dust.png',
  'ae2:printed_silicon':        'ae2/printed_silicon.png',
  'ae2:printed_calculation_processor':'ae2/printed_calculation_processor.png',
  'ae2:printed_engineering_processor':'ae2/printed_engineering_processor.png',
  'ae2:printed_logic_processor':'ae2/printed_logic_processor.png',
  'ae2:calculation_processor':  'ae2/calculation_processor.png',
  'ae2:engineering_processor':  'ae2/engineering_processor.png',
  'ae2:logic_processor':        'ae2/logic_processor.png',
  'ae2:cell_component_1k':      'ae2/cell_component_1k.png',
  'ae2:cell_component_4k':      'ae2/cell_component_4k.png',
  'ae2:cell_component_16k':     'ae2/cell_component_16k.png',
  'ae2:cell_component_64k':     'ae2/cell_component_64k.png',
  'ae2:cell_component_256k':    'ae2/cell_component_256k.png',
  'ae2:item_cell_housing':      'ae2/item_cell_housing.png',
  'ae2:fluid_cell_housing':     'ae2/fluid_cell_housing.png',

  // ─── IC2 ───
  'ic2:refined_iron_ingot':     'ic2/refined_iron_ingot.png',
  'ic2:carbon_plate':           'ic2/carbon_plate.png',
  'ic2:rubber':                 'ic2/rubber.png',
  'ic2:insulated_copper_cable': 'ic2/insulated_copper_cable.png',
  'ic2:glass_fibre_cable':      'ic2/glass_fibre_cable.png',
  'ic2:electronic_circuit':     'ic2/electronic_circuit.png',
  'ic2:advanced_circuit':       'ic2/advanced_circuit.png',
  'ic2:machine_block_basic':    'ic2/machine_block_basic.png',
  'ic2:machine_block_advanced': 'ic2/machine_block_advanced.png',
  'ic2:generator':              'ic2/generator.png',
  'ic2:solar_panel':            'ic2/solar_panel.png',
  'ic2:cesu':                   'ic2/cesu.png',
  'ic2:mf_unit':                'ic2/mf_unit.png',
  'ic2:mfs_unit':               'ic2/mfs_unit.png',
  'ic2:storage_battery':        'ic2/storage_battery.png',
};

export function getItemTexture(itemId: string): string | undefined {
  const path = TEXTURE_MAP[itemId];
  if (!path) return undefined;
  return `${import.meta.env.BASE_URL}textures/${path}`;
}
